image: docker:latest
   
stages:
  - test
  - build

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  CI_REGISTRY: "https://index.docker.io/v1"
  CI_REGISTRY_IMAGE: "docker.io/peterducai/aidb"

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

test_build:
  stage: test
  tags: 
    - docker
  script:
    - docker build -t $IMAGE_TAG -t $CI_REGISTRY_IMAGE:latest .

build:
  stage: build
  tags: 
    - docker
  script:
    - docker build -t $IMAGE_TAG -t $CI_REGISTRY_IMAGE:latest .
    - docker push $IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master


